from __future__ import annotations

import csv
from dataclasses import dataclass
import json
from pathlib import Path
import textwrap
from typing import Any


@dataclass
class TaskPlan:
    instruction: str
    operations: list[str]
    assumptions: list[str]


class DataAutomationEngine:
    def _read_csv(self, file_path: Path) -> tuple[list[str], list[dict[str, str]]]:
        with file_path.open(newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
            return list(reader.fieldnames or []), rows

    def profile_file(self, file_path: Path, sample_rows: int = 10) -> dict[str, Any]:
        columns, rows = self._read_csv(file_path)
        return {
            "path": str(file_path),
            "rows": len(rows),
            "columns": len(columns),
            "headers": columns,
            "sample": rows[:sample_rows],
        }

    def build_plan(self, instruction: str, inputs: list[Path]) -> TaskPlan:
        lower = instruction.lower()
        operations: list[str] = []
        assumptions: list[str] = []
        rules = {
            "join": ["join", "merge", "combine"],
            "union": ["union", "append"],
            "transform": ["etl", "clean", "transform"],
            "analyze": ["analy", "summary", "insight", "question"],
            "datascience": ["model", "predict", "forecast"],
            "pipeline": ["pipeline", "schedule", "scheduled query"],
            "diagram": ["diagram", "flowchart", "visual"],
        }
        for op, keywords in rules.items():
            if any(word in lower for word in keywords):
                operations.append(op)

        if not operations:
            operations.append("analyze")

        assumptions.append(f"Received {len(inputs)} input dataset(s).")
        assumptions.append("Generated script uses CSV + Python standard library by default.")
        return TaskPlan(instruction=instruction, operations=operations, assumptions=assumptions)

    def generate_script(self, plan: TaskPlan, inputs: list[Path], output_script: Path, output_data: str) -> str:
        script = textwrap.dedent(
            f'''\
            """Auto-generated by aiautomations.
            Instruction: {plan.instruction}
            Operations: {", ".join(plan.operations)}
            """

            import csv
            from pathlib import Path

            INPUTS = {[str(p) for p in inputs]!r}
            OUTPUT_PATH = {output_data!r}


            def load_rows(path):
                with open(path, newline="", encoding="utf-8") as f:
                    reader = csv.DictReader(f)
                    return list(reader.fieldnames or []), list(reader)


            def write_rows(path, headers, rows):
                Path(path).parent.mkdir(parents=True, exist_ok=True)
                with open(path, "w", newline="", encoding="utf-8") as f:
                    writer = csv.DictWriter(f, fieldnames=headers)
                    writer.writeheader()
                    writer.writerows(rows)


            def run():
                datasets = []
                for p in INPUTS:
                    headers, rows = load_rows(p)
                    datasets.append((Path(p).stem, headers, rows))

                if not datasets:
                    raise ValueError("No input files")

                headers, rows = datasets[0][1], datasets[0][2]
            '''
        )

        ops: list[str] = []
        if "join" in plan.operations:
            ops.extend(
                [
                    "# join scaffold: join first two datasets on first shared key",
                    "if len(datasets) > 1:",
                    "    _, h2, r2 = datasets[1]",
                    "    shared = [h for h in headers if h in h2]",
                    "    if shared:",
                    "        key = shared[0]",
                    "        index = {r.get(key): r for r in r2}",
                    "        joined = []",
                    "        for r in rows:",
                    "            if r.get(key) in index:",
                    "                merged = dict(r)",
                    "                for k, v in index[r[key]].items():",
                    "                    if k not in merged:",
                    "                        merged[k] = v",
                    "                joined.append(merged)",
                    "        rows = joined",
                    "        headers = list(rows[0].keys()) if rows else headers",
                ]
            )

        if "union" in plan.operations:
            ops.extend(
                [
                    "# union scaffold: append all rows with normalized headers",
                    "all_headers = set(headers)",
                    "for _, hs, _ in datasets[1:] :",
                    "    all_headers.update(hs)",
                    "all_headers = list(all_headers)",
                    "all_rows = []",
                    "for _, _, rs in datasets:",
                    "    for row in rs:",
                    "        all_rows.append({h: row.get(h, '') for h in all_headers})",
                    "headers, rows = all_headers, all_rows",
                ]
            )

        if "transform" in plan.operations:
            ops.extend(
                [
                    "# transform scaffold",
                    "cleaned = []",
                    "seen = set()",
                    "for row in rows:",
                    "    normalized = {k: (v.strip() if isinstance(v, str) else v) for k, v in row.items()}",
                    "    key = tuple((k, normalized.get(k, '')) for k in headers)",
                    "    if key not in seen:",
                    "        seen.add(key)",
                    "        cleaned.append(normalized)",
                    "rows = cleaned",
                ]
            )

        ops.extend(
            [
                "write_rows(OUTPUT_PATH, headers, rows)",
                "print(f'Wrote {len(rows)} rows to {OUTPUT_PATH}')",
            ]
        )

        script += textwrap.indent("\n".join(ops), "    ")
        script += "\n\nif __name__ == '__main__':\n    run()\n"
        output_script.write_text(script)
        return script

    def run_pipeline(self, pipeline_path: Path) -> list[str]:
        spec = json.loads(pipeline_path.read_text())
        steps = spec.get("steps", [])
        return [f"Step {i}: {step.get('type', 'unknown')}" for i, step in enumerate(steps, 1)]

    def generate_pipeline_diagram(self, pipeline_path: Path, output_path: Path) -> None:
        spec = json.loads(pipeline_path.read_text())
        steps = spec.get("steps", [])
        lines = ["flowchart TD"]
        for i, step in enumerate(steps, 1):
            lines.append(f'S{i}["{i}. {step.get("type", "unknown")}"]')
            if i > 1:
                lines.append(f"S{i-1} --> S{i}")
        output_path.write_text("\n".join(lines) + "\n")
